version: '3.8'

services:
  clip-node1:
    build: .
    container_name: clip-node1
    ports:
      - "8080:8080"
      - "9999:9999/udp"
    environment:
      - CLIP_ID=node1
      - CLIP_PORT=8080
      - CLIP_LOG_LEVEL=info
    networks:
      - clip-network
    restart: unless-stopped

  clip-node2:
    build: .
    container_name: clip-node2
    ports:
      - "8081:8080"
      - "10000:9999/udp"
    environment:
      - CLIP_ID=node2
      - CLIP_PORT=8080
      - CLIP_LOG_LEVEL=info
    networks:
      - clip-network
    restart: unless-stopped

  clip-node3:
    build: .
    container_name: clip-node3
    ports:
      - "8082:8080"
      - "10001:9999/udp"
    environment:
      - CLIP_ID=node3
      - CLIP_PORT=8080
      - CLIP_LOG_LEVEL=info
    networks:
      - clip-network
    restart: unless-stopped

networks:
  clip-network:
    driver: bridge